### ISSUE TITLE
Where is the database?

### ISSUE THREAD

**Issue by useraccessdenied** [cpuwhiz11/Voter#1]
In all of your php scripts you have mentioned mysql database queries, but I cannot find mysql db dump in your project!

**Comment by cpuwhiz11** [comment]
I never did a dump and this project is so old I do not have the schema any more. I suspect it was a very simple table with three columns (title, question, possibleResponses) all of type VARCHAR. The only interesting thing is it looks like possibleResponses was an ArrayList, but was converted to a string for storage in mysql. 

Given the age of the project I do not plan on updating it any further.

**Comment by useraccessdenied** [comment]
Thanks for your efforts though. I will create it myself then.
